version: '3.8'
services:

  postgres:
    image: postgres:11.5-alpine
    network_mode: host
    restart: always
    volumes:
      - stihi-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB=stihi
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGPORT=5432
    ports:
      - 5432:5432

  redis:
    image: redis:6.0.9
    network_mode: host
    restart: always
    volumes:
      - stihi-redis:/data
    ports:
      - 6379:6379

  stihi-base:
    image: stihi-base
    build:
      context: .
      dockerfile: ./Dockerfile

  stihi-backend:
    network_mode: host
    restart: always
    image: stihi-base:latest
    ports:
      - 9001:9001
      - 9095:9095
    volumes:
      - ./configs:/configs
    tmpfs:
      - /var/tmp
    depends_on:
      - stihi-base
      - redis
      - postgres
    command:
      - stihi-backend
      - -db_config=/configs/db_config.yaml
      - -mongo_db_config=/configs/mongo_db_config.yaml
      - -redis_config=/configs/redis_config.yaml
      - -config=/configs/stihi_backend_config.yaml

  blockchain-loader-cyberway:
    image: stihi-base:latest
    restart: always
    tmpfs:
      - /var/tmp
    volumes:
      - ./configs:/configs
    depends_on:
      - stihi-base
      - redis
      - postgres
    command:
      - blockchain_loader_cyberway
      - -db_config=/configs/db_config.yaml
      - -redis_config=/configs/redis_config.yaml
      - -config=/configs/stihi_backend_config.yaml

  scan_blockchain_cyberway:
    image: stihi-base:latest
    restart: always
    tmpfs:
      - /var/tmp
    volumes:
      - ./configs:/configs
    depends_on:
      - stihi-base
      - redis
      - postgres
    command:
      - scan_blockchain_cyberway
      - -db_config=/configs/db_config.yaml
      - -mongo_db_config=/configs/mongo_db_config.yaml
      - -redis_config=/configs/redis_config.yaml
      - -config=/configs/stihi_backend_config.yaml

volumes:
 stihi-postgres:
   external: true
 stihi-redis:
   external: true